export const FETCH_TODOS = 'FETCH_TODOS';
export const FETCH_TODOS_COMMIT = 'FETCH_TODOS_COMMIT';
export const FETCH_TODOS_ROLLBACK = 'FETCH_TODOS_ROLLBACK';

export const ADD_TODO = 'ADD_TODO';
export const ADD_TODO_COMMIT = 'ADD_TODO_COMMIT';
export const ADD_TODO_ROLLBACK = 'ADD_TODO_ROLLBACK';

export const UPDATE_TODO = 'UPDATE_TODO';
export const UPDATE_TODO_COMMIT = 'UPDATE_TODO_COMMIT';
export const UPDATE_TODO_ROLLBACK = 'UPDATE_TODO_ROLLBACK';